/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Pivotal tc Runtime 3.2.8.RELEASE/8.5.23.A.RELEASE
 * Generated at: 2018-04-23 07:20:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.form2;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import lecture1.form02.*;

public final class register2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("lecture1.form02");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

String userid = "";
String name = "";
String password1;
String password2;
String email = "";
int department = 0;
String 에러메시지 = null;
request.setCharacterEncoding("UTF-8");
if (request.getMethod().equals("POST")) {
    userid = request.getParameter("userid");
    name =  request.getParameter("name");
    password1 = request.getParameter("password1");
    password2 = request.getParameter("password2");
    email = request.getParameter("email");
    String s = request.getParameter("department");
    department = Integer.parseInt(s);
    
    if (userid == null || userid.length() == 0) 
        에러메시지 = "사용자 아이디를 입력하세요";
    else if (name == null || name.length() == 0) 
        에러메시지 = "이름을 입력하세요";
    else if (password1 == null || password1.length() == 0) 
        에러메시지 = "비밀번호1을 입력하세요";
    else if (password2 == null || password2.length() == 0) 
        에러메시지 = "비밀번호2를 입력하세요";
    else if (password1.equals(password2) == false)
        에러메시지 = "비밀번호 불일치";
    else if (email == null || email.length() == 0) 
        에러메시지 = "이메일 주소를 입력하세요";
    else {
        User user = new User(userid, name, password1, email, department);
        session.setAttribute("user", user);
        response.sendRedirect("register2_success.jsp");
        return;
    }
}

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"></script>\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("  <style>\n");
      out.write("      body { font-family: 굴림체; }\n");
      out.write("      input.form-control, select.form-control { width: 200px; }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("\n");
      out.write("<h1>회원가입</h1>\n");
      out.write("<hr />\n");
      out.write("\n");
      out.write("<form method=\"post\">\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>사용자 아이디</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" name=\"userid\" value=\"");
      out.print( userid );
      out.write("\" />\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>이름</label>\n");
      out.write("    <input type=\"text\" class=\"form-control\" name=\"name\" value=\"");
      out.print( name );
      out.write("\" />\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>비밀번호1</label>\n");
      out.write("    <input type=\"password\" class=\"form-control\" name=\"password1\" />\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>비밀번호2</label>\n");
      out.write("    <input type=\"password\" class=\"form-control\" name=\"password2\" />\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>이메일</label>\n");
      out.write("    <input type=\"email\" class=\"form-control\" name=\"email\" value=\"");
      out.print( email );
      out.write("\" />\n");
      out.write("  </div>\n");
      out.write("  <div class=\"form-group\">\n");
      out.write("    <label>학과</label>\n");
      out.write("    <select class=\"form-control\" name=\"department\">\n");
      out.write("      <option value=\"1\" ");
      out.print( department == 1 ? "selected" : "" );
      out.write(">소프트웨어공학과</option>\n");
      out.write("      <option value=\"2\" ");
      out.print( department == 2 ? "selected" : "" );
      out.write(">컴퓨터공학과</option>\n");
      out.write("      <option value=\"3\" ");
      out.print( department == 3 ? "selected" : "" );
      out.write(">정보통신공학과</option>\n");
      out.write("      <option value=\"4\" ");
      out.print( department == 4 ? "selected" : "" );
      out.write(">글로컬IT공학과</option>\n");
      out.write("    </select>\n");
      out.write("  </div>\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary\">\n");
      out.write("    <i class=\"glyphicon glyphicon-ok\"></i> 회원가입\n");
      out.write("  </button>\n");
      out.write("</form>\n");
      out.write("\n");
      out.write("<hr />\n");
      out.write("\n");
 if (에러메시지 != null) { 
      out.write("\n");
      out.write("  <div class=\"alert alert-danger\">\n");
      out.write("    로그인 실패: ");
      out.print( 에러메시지 );
      out.write("\n");
      out.write("  </div>\n");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
